sudo: false
language: erlang
script: make all test

otp_release:
  - 18.0
  - 17.5
  - 17.4
  - 17.3
  - 17.0
  - R15B03
  - R15B01
  - R15B
  - R14B04
  - R14B03

branches:
        only:
              - master
